In [ ]:
#single dimensional arrays in numpy
import numpy as np
n1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(n1)

#multi dimensional arrays in numpy

n2 = np.array([   [1,2,3,4],
                  [5,6,7,8],
              [11,22,33,44]  ])
print(n2)


#type of array
print(type(n1))
print(type(n2))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 22 33 44]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
#initializing numpy arrays with zeros 

import numpy as np

n1 = np.zeros((1,2))
print(n1)

n2 = np.zeros((5,5))
print(n2)

[[0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#initializing numpy arrays with same number

import numpy as np

n1 = np.full((2,2),10)
print(n1)

[[10 10]
 [10 10]]


In [ ]:
#initializing numpy arrays with in a range

import numpy as np

n1 = np.arange(10,20)
print(n1)

n2 = np.arange(10,100,5)
print(n2)

[10 11 12 13 14 15 16 17 18 19]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
#initializing numpy arrays with random numbers

import numpy as np

n1 = np.random.randint(1,100,10)
print(n1)

[73 88 93 73 85 87 51 40 99 50]


In [ ]:
#checking shape of numpy arrays

import numpy as np

n1 = np.array([[1,2,3,4,5],[9,8,7,4,2]])
print(n1)
print(n1.shape)

#changing shape of numpy array
n1.shape = (5,2)
print(n1)
print(n1.shape)

n1.shape = (1,10)
print(n1)
print(n1.shape)

n1.shape = (10,1)
print(n1)
print(n1.shape)

[[1 2 3 4 5]
 [9 8 7 4 2]]
(2, 5)
[[1 2]
 [3 4]
 [5 9]
 [8 7]
 [4 2]]
(5, 2)
[[1 2 3 4 5 9 8 7 4 2]]
(1, 10)
[[1]
 [2]
 [3]
 [4]
 [5]
 [9]
 [8]
 [7]
 [4]
 [2]]
(10, 1)


In [ ]:
#joining numpy arrays

import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([60,70,80])
print(np.vstack((n1,n2)))

import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([60,70,80])
print(np.hstack((n1,n2)))

import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([60,70,80])
print(np.column_stack((n1,n2)))

[[10 20 30]
 [60 70 80]]
[10 20 30 60 70 80]
[[10 60]
 [20 70]
 [30 80]]


In [ ]:
#numpy intersection and difference

import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90,100])

print(np.intersect1d(n1,n2))

print(np.setdiff1d(n1,n2))

print(np.setdiff1d(n2,n1))

[50 60]
[10 20 30 40]
[ 70  80  90 100]


In [ ]:
#adding of numpy arrays

import numpy as np
n1 = np.array([[10,20,30,40],
               [50,60,70,80]])
print(np.sum(n1))

print(np.sum(n1,axis=0))

print(np.sum(n1,axis=1))


360
[ 60  80 100 120]
[100 260]


In [ ]:
#scalar operations in numpy arrays

import numpy as np

n1 = np.array([10,20,30])
n1 = n1 + 1
print(n1)

n2 = np.array([10,20,30])
n2 = n2 - 1
print(n2)

n3 = np.array([10,20,30])
n3 = n3 * 2
print(n3)

n4 = np.array([10,20,30])
n4 = n4 / 5
print(n4)


[11 21 31]
[ 9 19 29]
[20 40 60]
[2. 4. 6.]


In [ ]:
#numpy math functions

import numpy as np
n1 = np.array([10,20,30,40,50,60])
print(np.mean(n1))

print(np.std(n1))

print(np.median(n1))

35.0
17.07825127659933
35.0


In [ ]:
#How to save and load the numpy array

import numpy as np
n1 = np.array([10,20,30,40,50,60])
np.save('my_array',n1)

n2 = np.load('my_array.npy')
print(n2)

[10 20 30 40 50 60]
